all:
  hosts:
    node1:
      ansible_host: 192.168.10.6
      ip: 192.168.10.6
      access_ip: 192.168.10.6
    node2:
      ansible_host: 192.168.20.22
      ip: 192.168.20.22
      access_ip: 192.168.20.22
    node3:
      ansible_host: 192.168.30.7
      ip: 192.168.30.7
      access_ip: 192.168.30.7
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    kube_ingress:
      hosts:
      node2:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
